### PR TITLE
Fix strict standards warnings and notices

### PR DESCRIPTION
**Pull request by r-a-y**
Hi Marshall,

Here's a PR that fixes some strict standards warnings and notices.

Commit f2612fc can be considered a hack, but I do not know enough about the ICE stack to address this properly.  Feel free to fix this the right way :)

### CODE REVIEW

**Comment by MrMaz** [comment]
Are you seeing the `wp_register_*()` errors as PHP notices, or are they showing up in one of the theme developer plugin logs?

**Comment by r-a-y** [comment]
> Are you seeing the wp_register_*() errors as PHP notices, or are they showing up in one of the theme developer plugin logs?

PHP notices when `WP_DEBUG` is set to true.

**Comment by MrMaz** [comment]
I think I have the register stuff figured out. It's yet another thing that WordPress changed the rules on. You used to be allowed to _register_ styles and scripts anytime you want, and then _enqueue_ them later... now they are being strict about even registering them early.

I just need to monkey with the api code so it calls the WP register scripts later.

**Comment by r-a-y** [comment]
Don't you just :heart: WordPress?

**Comment by MrMaz** [comment]
The following fixes were made to Infinity core and merged into this repo:

Strict standards:
40345890b60a4520463a282d1db355f96b9ea04c
9cf2d5fab87fc044540db472fa5f5e44f338eedc

Asset registration issues:
8c036deb568c6c930acbfb2c0c45beafc34a69d2
a0262f84292600cbb7c4cee59072134f23bc1dbd

Thanks Ray ;)

**Pull request closed without merging**
